.PHONY: blender
blender:
# Blender follows Thumbnail Managing Standard 0.7.0 (https://specifications.freedesktop.org/thumbnail-spec/0.7.0/x116.html)
	rm -rf $(HOME)/.thumbnails
	rm -rf $(HOME)/Library/Application\ Support/Blender
